name: MacOS Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10.3.0'

    - name: Build the project
      run: |
        cabal update
        cabal build

    - name: Create macOS App Bundle
      run: |
        # Create the app bundle structure
        mkdir -p fluidSimulation.app/Contents/MacOS
        mkdir -p fluidSimulation.app/Contents/Resources

        # Add the executable inside the MacOS folder
        cp dist-newstyle/build/*/*/*/*/*/build/haskell-animation/haskell-animation fluidSimulation.app/Contents/MacOS/haskell-animation

        # Add Info.plist file
        cat <<EOT > fluidSimulation.app/Contents/Info.plist
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
          <dict>
            <key>CFBundleExecutable</key>
            <string>haskell-animation</string>
            <key>CFBundleIdentifier</key>
            <string>com.yourcompany.fluidSimulation</string>
            <key>CFBundleName</key>
            <string>Fluid Simulation</string>
            <key>CFBundleVersion</key>
            <string>1.0</string>
          </dict>
        </plist>
        EOT

        # Set the executable permission
        chmod +x fluidSimulation.app/Contents/MacOS/haskell-animation

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: haskell-animation
        path: fluidSimulation.app
