name: MacOs Build

on: 
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.4.8'
        cabal-version: '3.10.3.0'

    - name: Build the project
      run: |
        cabal update
        cabal build

    - name: Upload Executable
      uses: actions/upload-artifact@v3
      with:
        name: haskell-animation
        path: dist-newstyle/build/*/*/*/*/*/build/*
